#!/usr/bin/env python3
import sys
from urllib.parse import unquote

if len(sys.argv) > 1:
    for arg in sys.argv[1:]:
        sys.stdout.write(unquote(arg))
else:
    s = sys.stdin.read()
    sys.stdout.write(unquote(s))
